// Auto-generated by OnUI CLI - DO NOT EDIT
// Regenerate with: npx onui analyze

export type AppRoute =
  | '/'
  | '/about'
  | '/talks'
  | '/podcasts'
  | '/blog'
  | '/contact'
  | '/*';

export type AppRouteParams = {
  '/': never;
  '/about': never;
  '/talks': never;
  '/podcasts': never;
  '/blog': never;
  '/contact': never;
  '/*': never;
};

export interface OnUINavigateOptions<T extends AppRoute> {
  to: T;
  params?: AppRouteParams[T];
}

export type ApiEndpoint =
  | 'SELECT fetchBlogs'
  | 'SELECT fetchPodcasts'
  | 'SELECT fetchTalks';

export interface OnUIRoute {
  path: AppRoute;
  name: string;
  type: 'landing' | 'dashboard' | 'listing' | 'detail' | 'form' | 'settings' | 'auth' | 'admin' | 'other';
  description: string;
  isProtected: boolean;
}

export interface OnUIApi {
  endpoint: string;
  method: 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE';
  description: string;
  auth: 'required' | 'optional' | 'none';
}
